// Immutable capability snapshot assembly and publication (Module 4.5).
//
// Generated bytes are written only beneath a unique build-id staging directory.
// A platform-authored manifest is then read back and verified against the exact
// on-disk inventory before one same-filesystem rename publishes the complete
// snapshot. Final version directories are never created recursively or written
// file-by-file.

import { existsSync, lstatSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { z } from "zod";

import {
  type CapabilitySpec,
  capabilitySpecSchema,
  incarnationIdSchema,
} from "../registry/index.ts";
import {
  canonicalJson,
  compareFileEntries,
  contentDigest,
  sameOrderedStrings,
  snapshotContentDigest,
} from "./artifact-digests.ts";
import { assertContained, listSnapshotFiles } from "./artifact-inventory.ts";
import {
  createSafeStagingParent,
  publishDirectoryWithoutOverwrite,
} from "./artifact-publication.ts";
import { assertIssuedCapabilityGateResult, type CapabilityGateResult } from "./gate.ts";
import { SnapshotVerificationError } from "./snapshot-error.ts";
import { buildUnitPrompt } from "./unit-prompts.ts";
import type { GeneratedUnit, UnitDescriptor } from "./units.ts";

export { SnapshotVerificationError } from "./snapshot-error.ts";

const SNAPSHOT_MANIFEST_VERSION = 1;
const SNAPSHOT_MANIFEST_FILE = "snapshot.json";
const SPEC_FILE = "spec.json";
const FROZEN_BEHAVIORAL_TEST_FILE = "tests/behavioral.json";
const DERIVED_UNIT_FILES = [
  "item.ts",
  "create.ts",
  "read.ts",
  "update.ts",
  "delete.ts",
  "search.ts",
] as const;

export const DEFAULT_ARTIFACTS_ROOT = "capabilities";

const digestSchema = z.string().regex(/^sha256:[a-f0-9]{64}$/);
const buildIdSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/);
const snapshotFilePathSchema = z
  .string()
  .min(1)
  .refine(
    (path) =>
      !path.startsWith("/") &&
      !path.includes("\\") &&
      path.split("/").every((segment) => segment.length > 0 && segment !== "." && segment !== ".."),
    "snapshot file paths must be safe relative POSIX paths",
  );

const snapshotFileEntrySchema = z.strictObject({
  path: snapshotFilePathSchema,
  content_digest: digestSchema.optional(),
});

const dependencyGenerationProvenanceSchema = z.strictObject({
  capability_id: z.string().min(1),
  incarnation_id: incarnationIdSchema,
  version: z.number().int().positive(),
  snapshot_content_digest: digestSchema,
});

const unitGenerationProvenanceSchema = z.strictObject({
  active_context_digest: digestSchema,
  dependencies: z.array(dependencyGenerationProvenanceSchema),
});

export const snapshotManifestSchema = z.strictObject({
  manifest_version: z.literal(SNAPSHOT_MANIFEST_VERSION),
  capability_id: z.string().min(1),
  incarnation_id: incarnationIdSchema,
  version: z.number().int().positive(),
  build_id: buildIdSchema,
  behavioral_tier: z.enum(["on", "off"]),
  snapshot_content_digest: digestSchema,
  files: z.array(snapshotFileEntrySchema).min(1),
  unit_provenance: z.strictObject({
    "item.ts": unitGenerationProvenanceSchema,
    "create.ts": unitGenerationProvenanceSchema,
    "read.ts": unitGenerationProvenanceSchema,
    "update.ts": unitGenerationProvenanceSchema,
    "delete.ts": unitGenerationProvenanceSchema,
    "search.ts": unitGenerationProvenanceSchema,
  }),
});

export type SnapshotManifest = z.infer<typeof snapshotManifestSchema>;
export type SnapshotFileEntry = z.infer<typeof snapshotFileEntrySchema>;
export type UnitGenerationProvenance = z.infer<typeof unitGenerationProvenanceSchema>;

export interface PublishCapabilitySnapshotInput {
  readonly buildId: string;
  readonly spec: CapabilitySpec;
  readonly incarnationId: string;
  readonly version: number;
  readonly units: readonly GeneratedUnit[];
  readonly gate: CapabilityGateResult;
  readonly artifactsRoot?: string;
  /** Test-only fault seam immediately after verification and before rename. */
  readonly beforePublish?: (stagingDirectory: string) => void;
}

export interface VerifiedPublishedSnapshot {
  readonly artifactsPath: string;
  readonly directory: string;
  readonly buildId: string;
  readonly incarnationId: string;
  readonly version: number;
  readonly files: readonly string[];
  readonly manifest: SnapshotManifest;
  readonly snapshotContentDigest: string;
}

export interface VerifiedCapabilitySnapshot {
  readonly directory: string;
  readonly files: readonly string[];
  readonly manifest: SnapshotManifest;
  readonly spec: CapabilitySpec;
}

interface IssuedPublicationEvidence {
  readonly artifactsPath: string;
  readonly directory: string;
  readonly buildId: string;
  readonly incarnationId: string;
  readonly version: number;
  readonly files: readonly string[];
  readonly manifest: string;
  readonly snapshotContentDigest: string;
}

const verifiedPublicationEvidence = new WeakMap<
  VerifiedPublishedSnapshot,
  IssuedPublicationEvidence
>();

/**
 * Assemble, verify, and publish one immutable capability snapshot. The staging
 * directory and final directory share the same incarnation parent, so the final
 * rename cannot cross filesystems.
 */
export function publishCapabilitySnapshot(
  input: PublishCapabilitySnapshotInput,
): VerifiedPublishedSnapshot {
  const spec = capabilitySpecSchema.parse(input.spec);
  const incarnationId = incarnationIdSchema.parse(input.incarnationId);
  const version = z.number().int().positive().parse(input.version);
  const buildId = buildIdSchema.parse(input.buildId);
  assertIssuedCapabilityGateResult(input.gate);
  assertGeneratedUnitInventory(input.units);
  assertSuccessfulGate(input.gate);
  assertUnitsMatchGateVerdict(input.units, input.gate);

  const root = resolve(process.cwd(), input.artifactsRoot ?? DEFAULT_ARTIFACTS_ROOT);
  const incarnationDirectory = resolve(root, spec.id, incarnationId);
  assertContained(root, incarnationDirectory);
  const stagingParent = join(incarnationDirectory, ".staging");
  const stagingDirectory = join(stagingParent, buildId);
  const finalDirectory = join(incarnationDirectory, `v${version}`);

  createSafeStagingParent(root, spec.id, incarnationId);
  // `recursive: false` is the uniqueness guarantee: reusing a build id fails
  // before any byte is written into an existing staging candidate.
  mkdirSync(stagingDirectory);

  try {
    writeCandidateFiles(stagingDirectory, spec, input.units, input.gate);
    const manifest = writeSnapshotManifest({
      stagingDirectory,
      spec,
      incarnationId,
      version,
      buildId,
      units: input.units,
      gate: input.gate,
    });
    verifyCapabilitySnapshot(stagingDirectory, manifest);
    publishDirectoryWithoutOverwrite(stagingDirectory, finalDirectory, () => {
      input.beforePublish?.(stagingDirectory);
      // Close the fault/instrumentation seam with another disk read so a callback
      // cannot alter a byte between the first verdict and publication.
      verifyCapabilitySnapshot(stagingDirectory, manifest);
    });

    const verified = verifyCapabilitySnapshot(finalDirectory, manifest);
    const artifactsPath = `${join(input.artifactsRoot ?? DEFAULT_ARTIFACTS_ROOT, spec.id, incarnationId, `v${version}`)}/`;
    const publication: VerifiedPublishedSnapshot = {
      artifactsPath,
      directory: finalDirectory,
      buildId,
      incarnationId,
      version,
      files: verified.files,
      manifest: verified.manifest,
      snapshotContentDigest: verified.manifest.snapshot_content_digest,
    };
    verifiedPublicationEvidence.set(publication, {
      ...publication,
      files: [...publication.files],
      manifest: canonicalJson(publication.manifest),
    });
    return publication;
  } catch (error) {
    // A failed staging/verification path is never routable. Keep a successfully
    // verified staging directory only when the injected pre-publish fault fires,
    // because recovery work needs that exact crash-like state for acceptance.
    if (!input.beforePublish || !existsSync(stagingDirectory)) {
      rmSync(stagingDirectory, { recursive: true, force: true });
    }
    throw error;
  }
}

/** Read and verify a staged or published snapshot against its own manifest. */
export function verifyCapabilitySnapshot(
  directory: string,
  expectedManifest?: SnapshotManifest,
): VerifiedCapabilitySnapshot {
  const absoluteDirectory = resolve(directory);
  const manifest = readSnapshotManifest(absoluteDirectory);
  assertExpectedManifest(manifest, expectedManifest);
  assertManifestShape(manifest);
  const actualFiles = listSnapshotFiles(absoluteDirectory);
  assertExactDiskInventory(actualFiles, manifest);
  verifyManifestEntries(absoluteDirectory, manifest);
  assertSnapshotContentFingerprint(manifest);
  const spec = readCapabilitySpec(absoluteDirectory);
  if (spec.id !== manifest.capability_id) {
    throw new SnapshotVerificationError("spec.json identity does not match snapshot.json.");
  }

  return { directory: absoluteDirectory, files: actualFiles, manifest, spec };
}

function readCapabilitySpec(directory: string): CapabilitySpec {
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(join(directory, SPEC_FILE), "utf8"));
  } catch (error) {
    throw new SnapshotVerificationError(
      `Invalid spec.json: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const parsed = capabilitySpecSchema.safeParse(value);
  if (!parsed.success) {
    throw new SnapshotVerificationError(`Invalid spec.json: ${parsed.error.message}`);
  }
  return parsed.data;
}

function readSnapshotManifest(directory: string): SnapshotManifest {
  const manifestPath = join(directory, SNAPSHOT_MANIFEST_FILE);
  if (!existsSync(manifestPath)) {
    throw new SnapshotVerificationError("Capability snapshot is missing snapshot.json.");
  }
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(manifestPath, "utf8"));
  } catch (error) {
    throw new SnapshotVerificationError(
      `Invalid snapshot.json: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const parsed = snapshotManifestSchema.safeParse(value);
  if (!parsed.success) {
    throw new SnapshotVerificationError(`Invalid snapshot.json: ${parsed.error.message}`);
  }
  return parsed.data;
}

function assertExpectedManifest(
  manifest: SnapshotManifest,
  expectedManifest: SnapshotManifest | undefined,
): void {
  if (expectedManifest && canonicalJson(manifest) !== canonicalJson(expectedManifest)) {
    throw new SnapshotVerificationError("Capability snapshot manifest changed after verification.");
  }
}

function assertExactDiskInventory(
  actualFiles: readonly string[],
  manifest: SnapshotManifest,
): void {
  const expectedFiles = manifest.files.map((entry) => entry.path);
  if (!sameOrderedStrings(actualFiles, expectedFiles)) {
    throw new SnapshotVerificationError(
      `Capability snapshot inventory mismatch: expected [${expectedFiles.join(", ")}], found [${actualFiles.join(", ")}].`,
    );
  }
}

function verifyManifestEntries(directory: string, manifest: SnapshotManifest): void {
  for (const entry of manifest.files) verifyManifestEntry(directory, entry);
}

function verifyManifestEntry(directory: string, entry: SnapshotFileEntry): void {
  const filePath = resolve(directory, entry.path);
  assertContained(directory, filePath);
  const stat = lstatSync(filePath);
  if (!stat.isFile() || stat.isSymbolicLink()) {
    throw new SnapshotVerificationError(`Snapshot entry ${entry.path} is not a regular file.`);
  }
  if (entry.path === SNAPSHOT_MANIFEST_FILE) return;
  if (contentDigest(readFileSync(filePath)) !== entry.content_digest) {
    throw new SnapshotVerificationError(
      `Snapshot entry ${entry.path} failed content verification.`,
    );
  }
}

function assertSnapshotContentFingerprint(manifest: SnapshotManifest): void {
  const contentEntries = manifest.files.filter(
    (entry): entry is SnapshotFileEntry & { content_digest: string } =>
      entry.path !== SNAPSHOT_MANIFEST_FILE && entry.content_digest !== undefined,
  );
  if (snapshotContentDigest(contentEntries) !== manifest.snapshot_content_digest) {
    throw new SnapshotVerificationError(
      "Snapshot content fingerprint does not match its inventory.",
    );
  }
}

/** Reverify the publication object immediately before a registry pointer consumes it. */
export function assertVerifiedPublishedSnapshot(
  publication: VerifiedPublishedSnapshot,
): VerifiedCapabilitySnapshot {
  const issued = verifiedPublicationEvidence.get(publication);
  if (!issued) {
    throw new SnapshotVerificationError(
      "Published snapshot evidence was not issued by publication.",
    );
  }
  if (
    publication.artifactsPath !== issued.artifactsPath ||
    publication.directory !== issued.directory ||
    publication.buildId !== issued.buildId ||
    publication.incarnationId !== issued.incarnationId ||
    publication.version !== issued.version ||
    publication.snapshotContentDigest !== issued.snapshotContentDigest ||
    !sameOrderedStrings(publication.files, issued.files) ||
    canonicalJson(publication.manifest) !== issued.manifest
  ) {
    throw new SnapshotVerificationError("Published snapshot evidence changed after issuance.");
  }
  const verified = verifyCapabilitySnapshot(publication.directory, publication.manifest);
  const expectedDirectory = resolve(publication.artifactsPath);
  const manifestDirectory = resolve(
    dirname(dirname(dirname(verified.directory))),
    verified.manifest.capability_id,
    verified.manifest.incarnation_id,
    `v${verified.manifest.version}`,
  );
  if (
    expectedDirectory !== verified.directory ||
    manifestDirectory !== verified.directory ||
    publication.buildId !== verified.manifest.build_id ||
    publication.incarnationId !== verified.manifest.incarnation_id ||
    publication.version !== verified.manifest.version ||
    publication.snapshotContentDigest !== verified.manifest.snapshot_content_digest ||
    !sameOrderedStrings(publication.files, verified.files)
  ) {
    throw new SnapshotVerificationError(
      "Published snapshot evidence does not match the final directory.",
    );
  }
  return verified;
}

function writeCandidateFiles(
  stagingDirectory: string,
  spec: CapabilitySpec,
  units: readonly GeneratedUnit[],
  gate: CapabilityGateResult,
): void {
  writeFileSync(join(stagingDirectory, SPEC_FILE), canonicalJson(spec));
  for (const unit of units) writeFileSync(join(stagingDirectory, unit.filename), unit.content);

  if (gate.behavioral.tier === "on") {
    const testDirectory = join(stagingDirectory, dirname(FROZEN_BEHAVIORAL_TEST_FILE));
    mkdirSync(testDirectory);
    writeFileSync(
      join(stagingDirectory, FROZEN_BEHAVIORAL_TEST_FILE),
      canonicalJson(gate.behavioral.frozenTests),
    );
  }
}

function writeSnapshotManifest(input: {
  readonly stagingDirectory: string;
  readonly spec: CapabilitySpec;
  readonly incarnationId: string;
  readonly version: number;
  readonly buildId: string;
  readonly units: readonly GeneratedUnit[];
  readonly gate: CapabilityGateResult;
}): SnapshotManifest {
  const otherFiles = listSnapshotFiles(input.stagingDirectory).map((path) => ({
    path,
    content_digest: contentDigest(readFileSync(join(input.stagingDirectory, path))),
  }));
  const files: SnapshotFileEntry[] = [{ path: SNAPSHOT_MANIFEST_FILE }, ...otherFiles].sort(
    compareFileEntries,
  );
  const manifest = snapshotManifestSchema.parse({
    manifest_version: SNAPSHOT_MANIFEST_VERSION,
    capability_id: input.spec.id,
    incarnation_id: input.incarnationId,
    version: input.version,
    build_id: input.buildId,
    behavioral_tier: input.gate.behavioral.tier,
    snapshot_content_digest: snapshotContentDigest(otherFiles),
    files,
    unit_provenance: unitProvenance(input.spec, input.units),
  });
  writeFileSync(join(input.stagingDirectory, SNAPSHOT_MANIFEST_FILE), canonicalJson(manifest));
  return manifest;
}

function unitProvenance(
  spec: CapabilitySpec,
  units: readonly GeneratedUnit[],
): SnapshotManifest["unit_provenance"] {
  // Fresh v1 capabilities cannot declare external dependencies. Later evolution
  // work will either regenerate with a verified dependency catalog or carry prior
  // provenance forward; silently inventing dependency evidence here would be false.
  for (const dependencies of Object.values(spec.read_dependencies)) {
    if (dependencies.length > 0) {
      throw new SnapshotVerificationError(
        "Dependency provenance requires a verified dependency snapshot catalog.",
      );
    }
  }

  const provenanceFor = (
    filename: (typeof DERIVED_UNIT_FILES)[number],
  ): UnitGenerationProvenance => {
    const unit = units.find((candidate) => candidate.filename === filename);
    if (!unit) throw new SnapshotVerificationError(`Missing derived unit ${filename}.`);
    const descriptor: UnitDescriptor =
      unit.kind === "handler"
        ? { kind: "handler", name: unit.name }
        : { kind: "item-renderer", name: "item" };
    return {
      active_context_digest: contentDigest(buildUnitPrompt(spec, descriptor)),
      dependencies: [],
    };
  };

  return {
    "item.ts": provenanceFor("item.ts"),
    "create.ts": provenanceFor("create.ts"),
    "read.ts": provenanceFor("read.ts"),
    "update.ts": provenanceFor("update.ts"),
    "delete.ts": provenanceFor("delete.ts"),
    "search.ts": provenanceFor("search.ts"),
  };
}

function assertSuccessfulGate(gate: CapabilityGateResult): void {
  const expected = ["structural", "smoke", "behavioral", "design-lint"] as const;
  if (
    gate.outcomes.length !== expected.length ||
    !gate.outcomes.every((outcome, index) => outcome.rung === expected[index])
  ) {
    throw new SnapshotVerificationError("Publication requires the complete canonical Gate result.");
  }
  for (const outcome of gate.outcomes) {
    const allowedSkipped = outcome.rung === "behavioral" && gate.behavioral.tier === "off";
    if (outcome.status !== "passed" && !(allowedSkipped && outcome.status === "skipped")) {
      throw new SnapshotVerificationError(
        `Publication requires a successful ${outcome.rung} Gate rung.`,
      );
    }
  }
  assertBehavioralGateMatchesTier(gate);
}

function assertUnitsMatchGateVerdict(
  units: readonly GeneratedUnit[],
  gate: CapabilityGateResult,
): void {
  for (const unit of units) {
    const gatedContent =
      unit.kind === "item-renderer" ? gate.designLint?.itemRenderer : gate.handlers?.[unit.name];
    if (gatedContent !== unit.content) {
      throw new SnapshotVerificationError(
        `Generated artifact ${unit.filename} does not match the bytes cleared by the Gate.`,
      );
    }
  }
}

function assertBehavioralGateMatchesTier(gate: CapabilityGateResult): void {
  const behavioralOutcome = gate.outcomes.find((outcome) => outcome.rung === "behavioral");
  const expectedStatus = gate.behavioral.tier === "on" ? "passed" : "skipped";
  if (gate.behavioral.status !== expectedStatus || behavioralOutcome?.status !== expectedStatus) {
    throw new SnapshotVerificationError(
      `Tier-${gate.behavioral.tier} publication requires a ${expectedStatus} behavioral Gate rung.`,
    );
  }
}

function assertGeneratedUnitInventory(units: readonly GeneratedUnit[]): void {
  const actual = units.map((unit) => unit.filename);
  if (!sameOrderedStrings(actual, DERIVED_UNIT_FILES)) {
    throw new SnapshotVerificationError(
      `Generated artifact inventory must be exactly ${DERIVED_UNIT_FILES.join(", ")} in order.`,
    );
  }
}

function assertManifestShape(manifest: SnapshotManifest): void {
  const snapshotEntries = manifest.files.filter((entry) => entry.path === SNAPSHOT_MANIFEST_FILE);
  if (snapshotEntries.length !== 1 || snapshotEntries[0]?.content_digest !== undefined) {
    throw new SnapshotVerificationError(
      "snapshot.json must appear exactly once without a self-digest.",
    );
  }
  const paths = manifest.files.map((entry) => entry.path);
  if (new Set(paths).size !== paths.length || !sameOrderedStrings(paths, [...paths].sort())) {
    throw new SnapshotVerificationError(
      "Snapshot inventory must be unique and canonically ordered.",
    );
  }
  const requiredPaths = [
    SNAPSHOT_MANIFEST_FILE,
    SPEC_FILE,
    ...DERIVED_UNIT_FILES,
    ...(manifest.behavioral_tier === "on" ? [FROZEN_BEHAVIORAL_TEST_FILE] : []),
  ].sort();
  if (!sameOrderedStrings(paths, requiredPaths)) {
    throw new SnapshotVerificationError(
      `Snapshot inventory must be exactly [${requiredPaths.join(", ")}] for tier ${manifest.behavioral_tier}.`,
    );
  }
  for (const entry of manifest.files) {
    if (entry.path !== SNAPSHOT_MANIFEST_FILE && entry.content_digest === undefined) {
      throw new SnapshotVerificationError(
        `Snapshot entry ${entry.path} is missing its content digest.`,
      );
    }
  }
}
