// Capability data-table infrastructure — Module 2, Epic 2.2.

export {
  applyCapabilityTableDdl,
  CAPABILITY_TABLE_PREFIX,
  type CapabilityTableDdl,
  deriveCapabilityTableDdl,
  SQLITE_TYPE_BY_FIELD_TYPE,
} from "./ddl.ts";
export {
  type CapabilityCreateValues,
  type CapabilityDeleteMutationPort,
  type CapabilityMutationPort,
  type CapabilityUpdateMutationPort,
  type CapabilityUpdateValues,
  createCapabilityDeleteMutationPort,
  createCapabilityMutationPort,
  createCapabilityUpdateMutationPort,
  RECORD_NOT_FOUND_ERROR_CODE,
  RecordNotFoundError,
} from "./mutation.ts";
export {
  type CapabilityActionRecord,
  type CapabilityDataColumnValue,
  type CapabilityDataRow,
  CapabilityDataValidationError,
  type CapabilityQueryInput,
  type CapabilityQueryParameter,
  type CapabilityQueryPort,
  type CapabilityQueryResultColumn,
  type CapabilityQueryResultType,
  type CapabilityQueryRow,
  type CapabilityQueryScope,
  type CapabilityRecordHandle,
  type CapabilityRecordQueryInput,
  type CapabilityRecordQueryRow,
  capabilityQueryScopeTableNames,
  createCapabilityActionRecord,
  createCapabilityQueryPort,
  encodeCapabilityFieldForStorage,
  isCapabilityActionRecord,
  MissingRequiredFieldsError,
  materializeCapabilityActionRecord,
  normalizeSearchText,
  selectCapabilityRows,
} from "./tool.ts";
