// The capability registry — Module 2, Epic 2.1 (ARCH §6.3, PLAN decision 8).
//
// The single public entry point for the registry subsystem: the validated spec
// shape every Module 2 piece consumes (DDL mapper, router, spec generation,
// behavioral tier) and the lean read/write access to the registry table. Later
// epics import from here and depend on nothing inside.

export { canonicalCapabilityLabel, isCapabilityNameLabel } from "./labels.ts";
export {
  activeSpecFields,
  BEHAVIORAL_ERROR_MARKERS,
  type BehavioralErrorCase,
  type BehavioralErrorMarkers,
  behavioralErrorCaseSchema,
  behavioralErrorMarkersSchema,
  type CapabilityRow,
  type CapabilitySpec,
  type CapabilityTool,
  CREATED_AT_DESCRIPTOR,
  capabilityRowSchema,
  capabilitySpecFromRow,
  capabilitySpecSchema,
  capabilityToolSchema,
  defaultBehavioralErrorsForSchema,
  type FieldLifecycle,
  type FieldType,
  FULL_CAPABILITY_TOOLS,
  fieldLifecycleSchema,
  fieldTypeSchema,
  incarnationIdSchema,
  isListFieldType,
  LIST_FIELD_TYPES,
  LIST_INPUT_MODES,
  type ListFieldType,
  type ListInputIntent,
  type ListInputMode,
  listInputIntentSchema,
  listInputModeSchema,
  MISSING_REQUIRED_FIELDS_ERROR_CODE,
  PLATFORM_COLUMNS,
  type PresentationFieldDescriptor,
  presentationFieldDescriptors,
  promptCapabilitySpecSchema,
  type ReadDependencies,
  type ReadDependency,
  readDependenciesSchema,
  readDependencySchema,
  SCALAR_FIELD_TYPES,
  type SpecField,
  specFieldSchema,
  type UiCollectionLayout,
  type UiFormIntent,
  type UiIntent,
  uiCollectionLayoutSchema,
  uiFormIntentSchema,
  uiIntentSchema,
} from "./spec.ts";
export {
  type CapabilityRegistryExpectation,
  compareAndSwapCapability,
  getCapability,
  insertCapability,
  isRegistryInitialized,
  listCapabilities,
  listCapabilityDependents,
  REGISTRY_TABLE,
  resolveActionReadDependencies,
  StaleCapabilityRegistryError,
} from "./store.ts";
