// The capability registry.
//
// The single public entry point for the registry subsystem: the validated spec
// shape every Module 2 piece consumes (DDL mapper, router, spec generation,
// behavioral tier) and the lean read/write access to the registry table. Later
// epics import from here and depend on nothing inside.

export {
  type ActiveRegistryCatalog,
  fingerprintActiveRegistryCatalog,
  readActiveRegistryCatalog,
} from "./active-catalog.ts";
export {
  type CapabilityDeletionTombstone,
  DELETION_TOMBSTONE_STATE,
  getCapabilityDeletionTombstone,
  insertCapabilityDeletionTombstone,
  isCapabilityIdReservedByDeletion,
  listCapabilityDeletionTombstones,
  type OwnedResourceEntry,
  recordCapabilityDeletionCleanupFailure,
  removeCapabilityDeletionTombstone,
} from "./deletion-tombstones.ts";
export { canonicalCapabilityLabel, isCapabilityNameLabel } from "./labels.ts";
export {
  type CapabilityLogoState,
  capabilityLogoStateSchema,
  createCapabilityLogoSeed,
  LOGO_BIRTH_STATUS,
  LOGO_FAMILY_SHADES,
  LOGO_HUE_FAMILIES,
  LOGO_MAX_CLAIMED_ATTEMPTS,
  LOGO_SHADES,
  LOGO_STATUSES,
  type LogoHueFamily,
  type LogoShade,
  type LogoStatus,
  logoHueFamilySchema,
  logoRequestColors,
  logoSeedSchema,
  logoShadeFamily,
  logoShadeSchema,
  MAX_LOGO_SEED,
  resolveLogoShades,
} from "./logo.ts";
export {
  activeSpecFields,
  BEHAVIORAL_ERROR_MARKERS,
  type BehavioralErrorCase,
  type BehavioralErrorMarkers,
  behavioralErrorCaseSchema,
  behavioralErrorMarkersSchema,
  type CapabilityRegistryWrite,
  type CapabilityRow,
  type CapabilitySpec,
  type CapabilityTool,
  CREATED_AT_DESCRIPTOR,
  capabilityRegistryWriteSchema,
  capabilityRowSchema,
  capabilitySpecFromRow,
  capabilitySpecSchema,
  capabilityToolSchema,
  defaultBehavioralErrorsForSchema,
  type FieldLifecycle,
  type FieldType,
  FULL_CAPABILITY_TOOLS,
  fieldLifecycleSchema,
  fieldTypeSchema,
  incarnationIdSchema,
  isListFieldType,
  LIST_FIELD_TYPES,
  LIST_INPUT_MODES,
  type ListFieldType,
  type ListInputIntent,
  type ListInputMode,
  listInputIntentSchema,
  listInputModeSchema,
  MAX_BEHAVIORAL_ERRORS,
  MAX_CAPABILITY_NOUN_LENGTH,
  MAX_LOGO_SUBJECT_LENGTH,
  MISSING_REQUIRED_FIELDS_ERROR_CODE,
  PLATFORM_COLUMNS,
  type PresentationFieldDescriptor,
  presentationFieldDescriptors,
  promptCapabilitySpecSchema,
  type ReadDependencies,
  type ReadDependency,
  readDependenciesSchema,
  readDependencySchema,
  SCALAR_FIELD_TYPES,
  type SpecField,
  specFieldSchema,
  type UiCollectionLayout,
  type UiFormIntent,
  type UiIntent,
  uiCollectionLayoutSchema,
  uiFormIntentSchema,
  uiIntentSchema,
} from "./spec.ts";
export {
  abandonMissingCapabilityLogo,
  type CapabilityRegistryExpectation,
  type CapabilityRegistryWriteInput,
  claimLogoGeneration,
  compareAndSwapCapability,
  getCapability,
  getCapabilityLogoState,
  insertCapability,
  isRegistryInitialized,
  type LogoGenerationClaim,
  listActiveIncarnations,
  listCapabilities,
  listCapabilityDependents,
  REGISTRY_TABLE,
  releaseLogoClaim,
  resolveActionReadDependencies,
  StaleCapabilityRegistryError,
  settleLogoGeneration,
} from "./store.ts";
