// The capability registry.
//
// The single public entry point for the registry subsystem: the validated spec
// shape every Module 2 piece consumes (DDL mapper, router, spec generation,
// behavioral tier) and the lean read/write access to the registry table. Later
// epics import from here and depend on nothing inside.

export {
  type ActiveRegistryCatalog,
  fingerprintActiveRegistryCatalog,
  readActiveRegistryCatalog,
} from "./active-catalog.ts";
export {
  BEHAVIORAL_ERROR_MARKERS,
  type BehavioralErrorCase,
  behavioralErrorCaseSchema,
  behavioralErrorMarkersSchema,
  defaultBehavioralErrorsForSchema,
  MAX_BEHAVIORAL_ERRORS,
  MISSING_REQUIRED_FIELDS_ERROR_CODE,
} from "./behavioral-errors.ts";
export {
  admittedChoiceValues,
  CHOICE_DISABLED_ERROR_CODE,
  CHOICE_FIELD_TYPE,
  CHOICE_PRESENTATIONS,
  type ChoiceFieldType,
  type ChoiceGroup,
  type ChoiceInputIntent,
  type ChoiceOption,
  type ChoiceOptionRun,
  type ChoicePresentation,
  choiceFieldGroups,
  choiceFieldOptions,
  choiceGroupSchema,
  choiceInputIntentSchema,
  choiceOptionRuns,
  choiceOptionSchema,
  choicePresentationSchema,
  INVALID_CHOICE_ERROR_CODE,
  isChoiceFieldType,
  MAX_CHOICE_GROUP_HEADING_LENGTH,
  MAX_CHOICE_GROUPS,
  MAX_CHOICE_OPTION_LABEL_LENGTH,
  MAX_CHOICE_OPTION_NOTE_LENGTH,
  MAX_CHOICE_OPTION_VALUE_LENGTH,
  MAX_CHOICE_OPTIONS,
  selectableChoiceValues,
} from "./choice.ts";
export {
  type CapabilityDeletionTombstone,
  DELETION_TOMBSTONE_STATE,
  getCapabilityDeletionTombstone,
  insertCapabilityDeletionTombstone,
  isCapabilityIdReservedByDeletion,
  listCapabilityDeletionTombstones,
  type OwnedResourceEntry,
  recordCapabilityDeletionCleanupFailure,
  removeCapabilityDeletionTombstone,
} from "./deletion-tombstones.ts";
export { incarnationIdSchema } from "./identifiers.ts";
export {
  canonicalCapabilityLabel,
  effectiveCapabilityLabel,
  isCapabilityNameLabel,
  MAX_CAPABILITY_LABEL_CHARS,
} from "./labels.ts";
export {
  type CapabilityLogoState,
  capabilityLogoStateSchema,
  createCapabilityLogoSeed,
  LOGO_BIRTH_STATUS,
  LOGO_FAMILY_SHADES,
  LOGO_HUE_FAMILIES,
  LOGO_MAX_CLAIMED_ATTEMPTS,
  LOGO_SHADES,
  LOGO_STATUSES,
  type LogoHueFamily,
  type LogoShade,
  type LogoStatus,
  logoHueFamilySchema,
  logoSeedSchema,
  logoShadeFamily,
  MAX_LOGO_SEED,
  resolveLogoShades,
} from "./logo.ts";
export {
  activeSpecFields,
  type BehavioralErrorMarkers,
  type CapabilityRegistryWrite,
  type CapabilityRow,
  type CapabilitySpec,
  CREATED_AT_DESCRIPTOR,
  canonicalizeStoredCapabilityShape,
  capabilityRegistryWriteSchema,
  capabilityRowSchema,
  capabilitySpecFromRow,
  capabilitySpecSchema,
  type FieldLifecycle,
  type FieldType,
  fieldLifecycleSchema,
  fieldTypeSchema,
  isListFieldType,
  LIST_FIELD_TYPES,
  LIST_INPUT_MODES,
  type ListFieldType,
  type ListInputIntent,
  type ListInputMode,
  listInputIntentSchema,
  listInputModeSchema,
  MAX_CAPABILITY_NOUN_LENGTH,
  MAX_LOGO_SUBJECT_LENGTH,
  PLATFORM_COLUMNS,
  type PresentationFieldDescriptor,
  presentationFieldDescriptors,
  promptCapabilitySpecSchema,
  SCALAR_FIELD_TYPES,
  type SpecField,
  specFieldSchema,
  type UiCollectionLayout,
  type UiFormIntent,
  type UiIntent,
  uiCollectionLayoutSchema,
  uiFormIntentSchema,
  uiIntentSchema,
} from "./spec.ts";
export {
  abandonMissingCapabilityLogo,
  type CapabilityRegistryExpectation,
  type CapabilityRegistryWriteInput,
  claimLogoGeneration,
  compareAndSwapCapability,
  getCapability,
  getCapabilityLogoState,
  insertCapability,
  isRegistryInitialized,
  type LogoGenerationClaim,
  listActiveIncarnations,
  listCapabilities,
  listCapabilityDependents,
  REGISTRY_TABLE,
  releaseLogoClaim,
  renameCapability,
  resolveActionReadDependencies,
  StaleCapabilityRegistryError,
  settleLogoGeneration,
} from "./store.ts";
export {
  type CapabilityTool,
  capabilityToolSchema,
  FULL_CAPABILITY_TOOLS,
  type ReadDependencies,
  type ReadDependency,
  readDependenciesSchema,
  readDependencySchema,
} from "./tools.ts";
