// Immutable capability snapshot assembly and publication.
//
// Generated bytes are written only beneath a unique build-id staging directory.
// A platform-authored manifest is then read back and verified against the exact
// on-disk inventory before one same-filesystem rename publishes the complete
// snapshot. Final version directories are never created recursively or written
// file-by-file.

import { existsSync, lstatSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { z } from "zod";

import {
  type CapabilitySpec,
  canonicalizeStoredCapabilityShape,
  capabilitySpecSchema,
  FULL_CAPABILITY_TOOLS,
  incarnationIdSchema,
} from "../../../registry/index.ts";
import { assertIssuedCapabilityGateResult, type CapabilityGateResult } from "../../gate/gate.ts";
import {
  BEHAVIORAL_EXECUTION_REASONS,
  type BehavioralExecutionPlan,
} from "../../gate/rungs/behavioral/freeze/behavioral-execution-plan.ts";
import {
  type FrozenBehavioralTests,
  frozenBehavioralTestsSchema,
} from "../../gate/rungs/behavioral/generation/gate-behavioral-full-schema.ts";
import type { GeneratedUnit } from "../../units/generation/units.ts";
import {
  canonicalJson,
  compareFileEntries,
  contentDigest,
  sameOrderedStrings,
  snapshotContentDigest,
} from "../inventory/artifact-digests.ts";
import { assertContained, listSnapshotFiles } from "../inventory/artifact-inventory.ts";
import {
  type UnitProvenanceManifest,
  unitProvenance,
  unitProvenanceManifestSchema,
} from "../inventory/artifact-provenance.ts";
import { SnapshotVerificationError } from "../inventory/snapshot-error.ts";
import {
  createSafeStagingParent,
  publishDirectoryWithoutOverwrite,
} from "./artifact-publication.ts";

export { SnapshotVerificationError } from "../inventory/snapshot-error.ts";

const SNAPSHOT_MANIFEST_VERSION = 1;

import {
  assertGeneratedUnitInventory,
  assertManifestShape,
  assertSuccessfulGate,
  assertUnitsMatchGateVerdict,
  FROZEN_BEHAVIORAL_TEST_FILE,
  SNAPSHOT_MANIFEST_FILE,
  SPEC_FILE,
} from "./snapshot-contract.ts";

export const DEFAULT_ARTIFACTS_ROOT = "capabilities";

const digestSchema = z.string().regex(/^sha256:[a-f0-9]{64}$/);
const buildIdSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]*$/);
const snapshotFilePathSchema = z
  .string()
  .min(1)
  .refine(
    (path) =>
      !path.startsWith("/") &&
      !path.includes("\\") &&
      path.split("/").every((segment) => segment.length > 0 && segment !== "." && segment !== ".."),
    "snapshot file paths must be safe relative POSIX paths",
  );

const snapshotFileEntrySchema = z.strictObject({
  path: snapshotFilePathSchema,
  content_digest: digestSchema.optional(),
});

/**
 * The tier metadata a tier-on snapshot records beyond the on/off flag: per Action,
 * where this version's frozen cases came from and whether they were re-proven against these
 * bytes. It lives here rather than inside `tests/behavioral.json` on purpose — the frozen
 * artifact must stay byte-identical when its inputs did not move, so a fact about *this
 * build's* execution cannot be written into it without destroying that guarantee.
 */
const snapshotBehavioralTestEntrySchema = z.strictObject({
  action: z.enum(FULL_CAPABILITY_TOOLS),
  source: z.enum(["generated", "copied"]),
  execution: z.enum(["executed", "skipped"]),
  // The closed reason vocabulary, pinned in the durable artifact rather than left as free
  // text: the run/skip decision is only auditable if its grounds are a fixed set.
  reason: z.enum(BEHAVIORAL_EXECUTION_REASONS),
});

const snapshotBehavioralTestsSchema = z.strictObject({
  /** True when execution could not be narrowed and the complete frozen suite ran. */
  full_suite: z.boolean(),
  full_suite_reason: z.string().min(1).optional(),
  actions: z.array(snapshotBehavioralTestEntrySchema).min(1).max(FULL_CAPABILITY_TOOLS.length),
});

export const snapshotManifestSchema = z.strictObject({
  manifest_version: z.literal(SNAPSHOT_MANIFEST_VERSION),
  capability_id: z.string().min(1),
  incarnation_id: incarnationIdSchema,
  version: z.number().int().positive(),
  build_id: buildIdSchema,
  behavioral_tier: z.enum(["on", "off"]),
  /** Present exactly when the tier is on; a tier-off snapshot has no tests to describe. */
  behavioral_tests: snapshotBehavioralTestsSchema.optional(),
  snapshot_content_digest: digestSchema,
  files: z.array(snapshotFileEntrySchema).min(1),
  unit_provenance: unitProvenanceManifestSchema,
});

export type SnapshotManifest = z.infer<typeof snapshotManifestSchema>;
export type SnapshotFileEntry = z.infer<typeof snapshotFileEntrySchema>;
export type { UnitGenerationProvenance } from "../inventory/artifact-provenance.ts";

export interface PublishCapabilitySnapshotInput {
  readonly buildId: string;
  readonly spec: CapabilitySpec;
  readonly incarnationId: string;
  readonly version: number;
  readonly units: readonly GeneratedUnit[];
  readonly gate: CapabilityGateResult;
  readonly artifactsRoot?: string;
  /**
   * The per-unit dependency-generation provenance this snapshot records. Omitted for a
   * fresh v1 build, whose every unit is new; an evolution supplies the manifest its Diff
   * settled, so a byte-copied unit carries its committed provenance forward instead of
   * having it silently recomputed against the candidate.
   */
  readonly unitProvenance?: UnitProvenanceManifest;
  /** Test-only fault seam immediately after verification and before rename. */
  readonly beforePublish?: (stagingDirectory: string) => void;
}

export interface VerifiedPublishedSnapshot {
  readonly artifactsPath: string;
  readonly directory: string;
  readonly buildId: string;
  readonly incarnationId: string;
  readonly version: number;
  readonly files: readonly string[];
  readonly manifest: SnapshotManifest;
  readonly snapshotContentDigest: string;
}

export interface VerifiedCapabilitySnapshot {
  readonly directory: string;
  readonly files: readonly string[];
  readonly manifest: SnapshotManifest;
  readonly spec: CapabilitySpec;
}

interface IssuedPublicationEvidence {
  readonly artifactsPath: string;
  readonly directory: string;
  readonly buildId: string;
  readonly incarnationId: string;
  readonly version: number;
  readonly files: readonly string[];
  readonly manifest: string;
  readonly snapshotContentDigest: string;
}

const verifiedPublicationEvidence = new WeakMap<
  VerifiedPublishedSnapshot,
  IssuedPublicationEvidence
>();

/**
 * Assemble, verify, and publish one immutable capability snapshot. The staging
 * directory and final directory share the same incarnation parent, so the final
 * rename cannot cross filesystems.
 */
export function publishCapabilitySnapshot(
  input: PublishCapabilitySnapshotInput,
): VerifiedPublishedSnapshot {
  const spec = capabilitySpecSchema.parse(input.spec);
  const incarnationId = incarnationIdSchema.parse(input.incarnationId);
  const version = z.number().int().positive().parse(input.version);
  const buildId = buildIdSchema.parse(input.buildId);
  assertIssuedCapabilityGateResult(input.gate);
  assertGeneratedUnitInventory(input.units);
  assertSuccessfulGate(input.gate);
  assertUnitsMatchGateVerdict(input.units, input.gate);

  const root = resolve(process.cwd(), input.artifactsRoot ?? DEFAULT_ARTIFACTS_ROOT);
  const incarnationDirectory = resolve(root, spec.id, incarnationId);
  assertContained(root, incarnationDirectory);
  const stagingParent = join(incarnationDirectory, ".staging");
  const stagingDirectory = join(stagingParent, buildId);
  const finalDirectory = join(incarnationDirectory, `v${version}`);

  createSafeStagingParent(root, spec.id, incarnationId);
  // `recursive: false` is the uniqueness guarantee: reusing a build id fails
  // before any byte is written into an existing staging candidate.
  mkdirSync(stagingDirectory);

  try {
    writeCandidateFiles(stagingDirectory, spec, input.units, input.gate);
    const manifest = writeSnapshotManifest({
      stagingDirectory,
      spec,
      incarnationId,
      version,
      buildId,
      units: input.units,
      gate: input.gate,
      ...(input.unitProvenance ? { unitProvenance: input.unitProvenance } : {}),
    });
    verifyCapabilitySnapshot(stagingDirectory, manifest);
    publishDirectoryWithoutOverwrite(stagingDirectory, finalDirectory, () => {
      input.beforePublish?.(stagingDirectory);
      // Close the fault/instrumentation seam with another disk read so a callback
      // cannot alter a byte between the first verdict and publication.
      verifyCapabilitySnapshot(stagingDirectory, manifest);
    });

    const verified = verifyCapabilitySnapshot(finalDirectory, manifest);
    const artifactsPath = `${join(input.artifactsRoot ?? DEFAULT_ARTIFACTS_ROOT, spec.id, incarnationId, `v${version}`)}/`;
    const publication: VerifiedPublishedSnapshot = {
      artifactsPath,
      directory: finalDirectory,
      buildId,
      incarnationId,
      version,
      files: verified.files,
      manifest: verified.manifest,
      snapshotContentDigest: verified.manifest.snapshot_content_digest,
    };
    verifiedPublicationEvidence.set(publication, {
      ...publication,
      files: [...publication.files],
      manifest: canonicalJson(publication.manifest),
    });
    return publication;
  } catch (error) {
    // A failed staging/verification path is never routable. Keep a successfully
    // verified staging directory only when the injected pre-publish fault fires,
    // because recovery work needs that exact crash-like state for acceptance.
    if (!input.beforePublish || !existsSync(stagingDirectory)) {
      rmSync(stagingDirectory, { recursive: true, force: true });
    }
    throw error;
  }
}

/** Read and verify a staged or published snapshot against its own manifest. */
export function verifyCapabilitySnapshot(
  directory: string,
  expectedManifest?: SnapshotManifest,
): VerifiedCapabilitySnapshot {
  const absoluteDirectory = resolve(directory);
  const manifest = readSnapshotManifest(absoluteDirectory);
  assertExpectedManifest(manifest, expectedManifest);
  assertManifestShape(manifest);
  const actualFiles = listSnapshotFiles(absoluteDirectory);
  assertExactDiskInventory(actualFiles, manifest);
  verifyManifestEntries(absoluteDirectory, manifest);
  assertSnapshotContentFingerprint(manifest);
  const spec = readCapabilitySpec(absoluteDirectory);
  if (spec.id !== manifest.capability_id) {
    throw new SnapshotVerificationError("spec.json identity does not match snapshot.json.");
  }

  return { directory: absoluteDirectory, files: actualFiles, manifest, spec };
}

/**
 * Read a verified snapshot's frozen behavioral tests, or `undefined` when that version was
 * built tier-off and therefore carries no test artifact at all. The snapshot
 * has already been verified against its manifest digests by the time this runs, so the
 * bytes are known-unmodified; parsing is still strict, because a shape the current platform
 * cannot admit must fail closed rather than silently carry stale intent forward.
 */
export function readFrozenBehavioralTests(
  verified: VerifiedCapabilitySnapshot,
): FrozenBehavioralTests | undefined {
  if (verified.manifest.behavioral_tier !== "on") return undefined;
  const path = join(verified.directory, FROZEN_BEHAVIORAL_TEST_FILE);
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    throw new SnapshotVerificationError(
      `Invalid ${FROZEN_BEHAVIORAL_TEST_FILE}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const parsed = frozenBehavioralTestsSchema.safeParse(value);
  if (!parsed.success) {
    throw new SnapshotVerificationError(
      `Invalid ${FROZEN_BEHAVIORAL_TEST_FILE}: ${parsed.error.message}`,
    );
  }
  return parsed.data;
}

function readCapabilitySpec(directory: string): CapabilitySpec {
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(join(directory, SPEC_FILE), "utf8"));
  } catch (error) {
    throw new SnapshotVerificationError(
      `Invalid spec.json: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  // A published snapshot is immutable, so an older `spec.json` is read forward rather than
  // rewritten: a form-intent collection added after it was written canonicalizes to empty,
  // which leaves its bytes — and therefore its content digest — untouched.
  const parsed = capabilitySpecSchema.safeParse(canonicalizeStoredCapabilityShape(value));
  if (!parsed.success) {
    throw new SnapshotVerificationError(`Invalid spec.json: ${parsed.error.message}`);
  }
  return parsed.data;
}

function readSnapshotManifest(directory: string): SnapshotManifest {
  const manifestPath = join(directory, SNAPSHOT_MANIFEST_FILE);
  if (!existsSync(manifestPath)) {
    throw new SnapshotVerificationError("Capability snapshot is missing snapshot.json.");
  }
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(manifestPath, "utf8"));
  } catch (error) {
    throw new SnapshotVerificationError(
      `Invalid snapshot.json: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  const parsed = snapshotManifestSchema.safeParse(value);
  if (!parsed.success) {
    throw new SnapshotVerificationError(`Invalid snapshot.json: ${parsed.error.message}`);
  }
  return parsed.data;
}

function assertExpectedManifest(
  manifest: SnapshotManifest,
  expectedManifest: SnapshotManifest | undefined,
): void {
  if (expectedManifest && canonicalJson(manifest) !== canonicalJson(expectedManifest)) {
    throw new SnapshotVerificationError("Capability snapshot manifest changed after verification.");
  }
}

function assertExactDiskInventory(
  actualFiles: readonly string[],
  manifest: SnapshotManifest,
): void {
  const expectedFiles = manifest.files.map((entry) => entry.path);
  if (!sameOrderedStrings(actualFiles, expectedFiles)) {
    throw new SnapshotVerificationError(
      `Capability snapshot inventory mismatch: expected [${expectedFiles.join(", ")}], found [${actualFiles.join(", ")}].`,
    );
  }
}

function verifyManifestEntries(directory: string, manifest: SnapshotManifest): void {
  for (const entry of manifest.files) verifyManifestEntry(directory, entry);
}

function verifyManifestEntry(directory: string, entry: SnapshotFileEntry): void {
  const filePath = resolve(directory, entry.path);
  assertContained(directory, filePath);
  const stat = lstatSync(filePath);
  if (!stat.isFile() || stat.isSymbolicLink()) {
    throw new SnapshotVerificationError(`Snapshot entry ${entry.path} is not a regular file.`);
  }
  if (entry.path === SNAPSHOT_MANIFEST_FILE) return;
  if (contentDigest(readFileSync(filePath)) !== entry.content_digest) {
    throw new SnapshotVerificationError(
      `Snapshot entry ${entry.path} failed content verification.`,
    );
  }
}

function assertSnapshotContentFingerprint(manifest: SnapshotManifest): void {
  const contentEntries = manifest.files.filter(
    (entry): entry is SnapshotFileEntry & { content_digest: string } =>
      entry.path !== SNAPSHOT_MANIFEST_FILE && entry.content_digest !== undefined,
  );
  if (snapshotContentDigest(contentEntries) !== manifest.snapshot_content_digest) {
    throw new SnapshotVerificationError(
      "Snapshot content fingerprint does not match its inventory.",
    );
  }
}

/** Reverify the publication object immediately before a registry pointer consumes it. */
export function assertVerifiedPublishedSnapshot(
  publication: VerifiedPublishedSnapshot,
): VerifiedCapabilitySnapshot {
  const issued = verifiedPublicationEvidence.get(publication);
  if (!issued) {
    throw new SnapshotVerificationError(
      "Published snapshot evidence was not issued by publication.",
    );
  }
  if (
    publication.artifactsPath !== issued.artifactsPath ||
    publication.directory !== issued.directory ||
    publication.buildId !== issued.buildId ||
    publication.incarnationId !== issued.incarnationId ||
    publication.version !== issued.version ||
    publication.snapshotContentDigest !== issued.snapshotContentDigest ||
    !sameOrderedStrings(publication.files, issued.files) ||
    canonicalJson(publication.manifest) !== issued.manifest
  ) {
    throw new SnapshotVerificationError("Published snapshot evidence changed after issuance.");
  }
  const verified = verifyCapabilitySnapshot(publication.directory, publication.manifest);
  const expectedDirectory = resolve(publication.artifactsPath);
  const manifestDirectory = resolve(
    dirname(dirname(dirname(verified.directory))),
    verified.manifest.capability_id,
    verified.manifest.incarnation_id,
    `v${verified.manifest.version}`,
  );
  if (
    expectedDirectory !== verified.directory ||
    manifestDirectory !== verified.directory ||
    publication.buildId !== verified.manifest.build_id ||
    publication.incarnationId !== verified.manifest.incarnation_id ||
    publication.version !== verified.manifest.version ||
    publication.snapshotContentDigest !== verified.manifest.snapshot_content_digest ||
    !sameOrderedStrings(publication.files, verified.files)
  ) {
    throw new SnapshotVerificationError(
      "Published snapshot evidence does not match the final directory.",
    );
  }
  return verified;
}

function writeCandidateFiles(
  stagingDirectory: string,
  spec: CapabilitySpec,
  units: readonly GeneratedUnit[],
  gate: CapabilityGateResult,
): void {
  writeFileSync(join(stagingDirectory, SPEC_FILE), canonicalJson(spec));
  for (const unit of units) writeFileSync(join(stagingDirectory, unit.filename), unit.content);

  if (gate.behavioral.tier === "on") {
    const testDirectory = join(stagingDirectory, dirname(FROZEN_BEHAVIORAL_TEST_FILE));
    mkdirSync(testDirectory);
    writeFileSync(
      join(stagingDirectory, FROZEN_BEHAVIORAL_TEST_FILE),
      canonicalJson(gate.behavioral.frozenTests),
    );
  }
}

function writeSnapshotManifest(input: {
  readonly stagingDirectory: string;
  readonly spec: CapabilitySpec;
  readonly incarnationId: string;
  readonly version: number;
  readonly buildId: string;
  readonly units: readonly GeneratedUnit[];
  readonly gate: CapabilityGateResult;
  readonly unitProvenance?: UnitProvenanceManifest;
}): SnapshotManifest {
  const otherFiles = listSnapshotFiles(input.stagingDirectory).map((path) => ({
    path,
    content_digest: contentDigest(readFileSync(join(input.stagingDirectory, path))),
  }));
  const files: SnapshotFileEntry[] = [{ path: SNAPSHOT_MANIFEST_FILE }, ...otherFiles].sort(
    compareFileEntries,
  );
  const manifest = snapshotManifestSchema.parse({
    manifest_version: SNAPSHOT_MANIFEST_VERSION,
    capability_id: input.spec.id,
    incarnation_id: input.incarnationId,
    version: input.version,
    build_id: input.buildId,
    behavioral_tier: input.gate.behavioral.tier,
    ...(input.gate.behavioral.tier === "on"
      ? { behavioral_tests: behavioralTestMetadata(input.gate.behavioral.execution) }
      : {}),
    snapshot_content_digest: snapshotContentDigest(otherFiles),
    files,
    unit_provenance: input.unitProvenance ?? unitProvenance(input.spec, input.units),
  });
  writeFileSync(join(input.stagingDirectory, SNAPSHOT_MANIFEST_FILE), canonicalJson(manifest));
  return manifest;
}

/**
 * Project the Gate's execution plan into the manifest's snake_case record. The snapshot is
 * the durable answer to "was this version's frozen intent actually re-proven against these
 * bytes, or carried on the strength of unchanged Handlers?" — a question a later reader of
 * the artifacts cannot reconstruct from the frozen tests alone.
 */
function behavioralTestMetadata(
  execution: BehavioralExecutionPlan,
): z.infer<typeof snapshotBehavioralTestsSchema> {
  return {
    full_suite: execution.fullSuite,
    ...(execution.fullSuiteReason ? { full_suite_reason: execution.fullSuiteReason } : {}),
    actions: execution.actions.map((entry) => ({
      action: entry.action,
      source: entry.source,
      execution: entry.execution,
      reason: entry.reason,
    })),
  };
}
